-- Per-camera AI model toggles + crowd ROI zone (run once on existing DBs)
-- PostgreSQL

ALTER TABLE cameras ADD COLUMN IF NOT EXISTS person_detection_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE cameras ADD COLUMN IF NOT EXISTS crowd_roi_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE cameras ADD COLUMN IF NOT EXISTS crowd_roi_x1 DOUBLE PRECISION NOT NULL DEFAULT 0.22;
ALTER TABLE cameras ADD COLUMN IF NOT EXISTS crowd_roi_y1 DOUBLE PRECISION NOT NULL DEFAULT 0.28;
ALTER TABLE cameras ADD COLUMN IF NOT EXISTS crowd_roi_x2 DOUBLE PRECISION NOT NULL DEFAULT 0.78;
ALTER TABLE cameras ADD COLUMN IF NOT EXISTS crowd_roi_y2 DOUBLE PRECISION NOT NULL DEFAULT 0.72;
ALTER TABLE cameras ADD COLUMN IF NOT EXISTS last_crowd_roi_count INTEGER NOT NULL DEFAULT 0;
